# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='友链分类名称')),
            ],
            options={
                'verbose_name': '友链分类',
                'verbose_name_plural': '友链分类',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='简单描述')),
                ('url', models.URLField(verbose_name='链接')),
                ('logo_url', models.URLField(verbose_name='logo链接')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.FriendCategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('index', models.IntegerField(verbose_name='顺序')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('parents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.NavigationBar', verbose_name='父级导航')),
            ],
            options={
                'verbose_name': '导航栏设置',
                'verbose_name_plural': '导航栏设置',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('site_description', models.CharField(max_length=200, verbose_name='网站简介')),
                ('keywords', models.CharField(max_length=300, verbose_name='关键字')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='base/image/%y/%m', verbose_name='icon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='base/image/%y/%m', verbose_name='顶部logo')),
                ('f_logo', models.ImageField(blank=True, null=True, upload_to='base/image/%y/%m', verbose_name='底部logo')),
                ('site_copyright', models.CharField(max_length=50, verbose_name='版权')),
                ('icp', models.CharField(blank=True, max_length=20, null=True, verbose_name='备案号')),
                ('analytics_code', models.TextField(blank=True, max_length=1000, null=True, verbose_name='网站统计代码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '网站基础信息',
                'verbose_name_plural': '网站基础信息',
            },
        ),
    ]
