# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlink',
            options={'verbose_name': '友链设置', 'verbose_name_plural': '友链设置'},
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='f_logo',
            field=models.ImageField(blank=True, null=True, upload_to='base/image/%Y/%m', verbose_name='底部logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='base/image/%Y/%m', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='base/image/%Y/%m', verbose_name='顶部logo'),
        ),
    ]
