# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190407_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='avatar',
            field=models.ImageField(blank=True, help_text='主页中间和内容页底部显示的头像', null=True, upload_to='base/image/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='f_logo',
            field=models.ImageField(blank=True, help_text='网站底部旋转logo', null=True, upload_to='base/image/%Y/%m', verbose_name='底部logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, help_text='网站的favicon', null=True, upload_to='base/image/%Y/%m', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='导航栏最左侧跳动的logo', null=True, upload_to='base/image/%Y/%m', verbose_name='顶部logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_copyright',
            field=models.CharField(help_text='可以使用a标签的形式添加需要跳转的链接', max_length=50, verbose_name='版权'),
        ),
    ]
