# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190417_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationbar',
            name='parents',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='hitokoto_status',
            field=models.BooleanField(default=True, verbose_name='是否启用自动获取一言,默认打开'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='avatar',
            field=models.ImageField(blank=True, help_text='主页中间和内容页底部显示的头像', null=True, upload_to='image/private/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='f_logo',
            field=models.ImageField(blank=True, help_text='网站底部旋转logo', null=True, upload_to='image/private/', verbose_name='底部logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, help_text='网站的favicon', null=True, upload_to='image/private/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='导航栏最左侧跳动的logo', null=True, upload_to='image/private/', verbose_name='顶部logo'),
        ),
        migrations.DeleteModel(
            name='NavigationBar',
        ),
    ]
