# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1_url', models.URLField(help_text='跳转到的链接', verbose_name='链接')),
                ('feature1_title', models.CharField(max_length=20, verbose_name='标题')),
                ('feature1_image_url', models.URLField(help_text='要展示的图片的链接', verbose_name='图片链接')),
            ],
            options={
                'verbose_name': '推荐框信息',
                'verbose_name_plural': '推荐框信息',
            },
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(help_text='首页背景图', upload_to='images/bg/', verbose_name='背景图')),
                ('hitokoto', models.CharField(help_text='hitokoto一言,默认会使用ajax自动获取,可从基础配置中关闭', max_length=200, verbose_name='一言')),
                ('notice', models.CharField(blank=True, help_text='通知框中展示的内容', max_length=300, null=True, verbose_name='通知')),
                ('wechat_image', models.ImageField(help_text='微信二维码,社交信息中选择打开微信时才会有效', upload_to='image/private/', verbose_name='微信二维码')),
            ],
            options={
                'verbose_name': '首页其他信息',
                'verbose_name_plural': '首页其他信息',
            },
        ),
        migrations.CreateModel(
            name='SocialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bilibili', 'bilibili'), ('douban', '豆瓣'), ('facebook', 'facebook'), ('github', 'github'), ('lofter', 'lofter'), ('qq', 'qq'), ('qzone', 'QQ空间'), ('sina', '微博'), ('twitter', 'twitter'), ('wangyiyun', '网易云'), ('wechat', 'wechat'), ('zhihu', '知乎')], max_length=1)),
                ('url', models.URLField(help_text='跳转到的链接', verbose_name='链接')),
                ('index', models.IntegerField(default=0, help_text='越大越靠后', verbose_name='排序')),
            ],
            options={
                'verbose_name': '社交信息',
                'verbose_name_plural': '社交信息',
                'ordering': ['index', 'pk'],
            },
        ),
    ]
